# Generated by Django 5.1.5 on 2025-02-06 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0002_category_alter_task_created_task_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="datecompleted",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
