# Generated by Django 5.1.5 on 2025-02-20 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0005_commitment_invitation_notification_step_delete_task"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commitment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pendente"),
                    ("in_progress", "Em Andamento"),
                    ("completed", "Concluído"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
