# Generated by Django 5.1.5 on 2025-03-12 21:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0008_alter_commitment_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="commitment",
            name="convidados",
            field=models.ManyToManyField(
                blank=True,
                related_name="commitments_convidados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
